[package]

name          = "tokio-proto"
version       = "0.1.0"
license       = "MIT/Apache-2.0"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = """
A network application framework for rapid development and highly scalable
production deployments of clients and servers.
"""

documentation = "http://rust-doc.s3-website-us-east-1.amazonaws.com/tokio/master/tokio"
homepage      = "https://github.com/tokio-rs/tokio-proto"
repository    = "https://github.com/tokio-rs/tokio-proto"
readme        = "README.md"
keywords      = [ "io", "async", "non-blocking", "futures" ]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
bytes = { git = "https://github.com/carllerche/bytes" }
futures = { git = "https://github.com/alexcrichton/futures-rs" }
log = "0.3.6"
slab = { git = "https://github.com/carllerche/slab" }
take = "0.1.0"
tokio-core = { git = "https://github.com/tokio-rs/tokio-core" }
tokio-service = { git = "https://github.com/tokio-rs/tokio-service" }

[dev-dependencies]
env_logger = "0.3.0"
lazycell = { git = "https://github.com/carllerche/lazycell" }
mio = { git = "https://github.com/carllerche/mio" }

[[test]]
name = "test"
path = "test/mod.rs"
